### ISSUE TITLE
vagrant up fails as https://git.cloudstuff.se is nolonger available

### ISSUE THREAD

**Issue by pbgben** [NottingHack/hms2#548]
```
    default:   [RuntimeException]
    default:   Failed to execute git clone --mirror 'https://git.cloudstuff.se/composer/guzzle-oauth2-plugin' '/home/vagrant/.cache/composer/vcs/https---git.cloudstuff.se-composer-guzzle-oauth2-plugin/'
    default:
    default:   Cloning into bare repository '/home/vagrant/.cache/composer/vcs/https---git.cloudstuff.se-composer-guzzle-oauth2-plugin'...
    default:   fatal: unable to access 'https://git.cloudstuff.se/composer/guzzle-oauth2-plugin/': Failed to connect to git.cloudstuff.se port 443: Connection timed out
```
